apiVersion: v1
kind: Service
metadata:
  name: signed-app
  namespace: demo
  labels:
    app: signed-app
spec:
  type: ClusterIP
  selector:
    app: signed-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
